### ISSUE TITLE
Connect to database sql server

### ISSUE THREAD

**Issue by toanhk** [NguyenmanhIT/PrCafe#3]
Hi Mạnh,

Em cài thêm phần sqlConfiguration vào nhé (À em thử lại với chuỗi connection ở dưới xem sao? bỏ port đi). Chuỗi connection của thầy đây:  
public static Connection getConnection() throws SQLException {
        return DriverManager.getConnection(
                "jdbc:sqlserver://localhost:50645;instance=SQLEXPRESS;databaseName=T1703E_AAD2", "sa", "12345678");
    }

**Comment by nguyenvanmanh1368** [comment]
closed
